--=============================================
-- Atelier Civ / City List
--=============================================
INSERT OR REPLACE INTO LocalizedText
        (Tag,								Language,	Text)
VALUES	("LOC_CITY_NAME_SAILOR_ARLAND",		"en_US",	"Arland"),
		("LOC_CITY_NAME_SAILOR_RIESENGANG", "en_US",	"Riesengang"),
		("LOC_CITY_NAME_SAILOR_VIERZEBERG", "en_US",	"Vierzeberg"),
		("LOC_CITY_NAME_SAILOR_HORNHEIM",	"en_US",	"Hornheim"),
		("LOC_CITY_NAME_SAILOR_ALANYA",		"en_US",	"Alanya"),
		("LOC_CITY_NAME_SAILOR_FLUSSHEIM",	"en_US",	"Flussheim"),
		("LOC_CITY_NAME_SAILOR_FLOCKE",		"en_US",	"Flocke"),
		("LOC_CITY_NAME_SAILOR_WEISSLARK",	"en_US",	"Weisslark"),
		("LOC_CITY_NAME_SAILOR_GRAU_TAL",	"en_US",	"Grau-Tal"),
		("LOC_CITY_NAME_SAILOR_MERVEILLE",	"en_US",	"Merveille"),
		("LOC_CITY_NAME_SAILOR_KIRCHEN_BELL", "en_US",	"Kirchen Bell"),
		("LOC_CITY_NAME_SAILOR_STELLARD",	"en_US",	"Stellard"),
		("LOC_CITY_NAME_SAILOR_ARLS",		"en_US",	"Arls"),
		("LOC_CITY_NAME_SAILOR_SALBURG",	"en_US",	"Salburg"),
		("LOC_CITY_NAME_SAILOR_GRAMNAD",	"en_US",	"Gramnad"),
		("LOC_CITY_NAME_SAILOR_KANALLAND",	"en_US",	"Kanalland"),
		("LOC_CITY_NAME_SAILOR_KAROTTE",	"en_US",	"Karotte"),
		("LOC_CITY_NAME_SAILOR_REGALLZINE", "en_US",	"Regallzine"),
		("LOC_CITY_NAME_SAILOR_ZEY_MERUZE", "en_US",	"Zey Meruze"),
		("LOC_CITY_NAME_SAILOR_AL_REVIS",	"en_US",	"Al-Revis"),
		("LOC_CITY_NAME_SAILOR_ARKLYS",		"en_US",	"Arklys"),
		("LOC_CITY_NAME_SAILOR_ERTONA",		"en_US",	"Ertona"),
		("LOC_CITY_NAME_SAILOR_LUGION",		"en_US",	"Lugion"),
		("LOC_CITY_NAME_SAILOR_MYSLEE",		"en_US",	"Myslee"),
		("LOC_CITY_NAME_SAILOR_VESTABALT",	"en_US",	"Vestabalt"),
		("LOC_CITY_NAME_SAILOR_BRESSISLE",	"en_US",	"Bressisle"),
		("LOC_CITY_NAME_SAILOR_REISENBERG",	"en_US",	"Reisenberg"),
		("LOC_CITY_NAME_SAILOR_LUGION",		"en_US",	"Lugion"),
		("LOC_CITY_NAME_SAILOR_COLSEIT",	"en_US",	"Colseit"),
		("LOC_CITY_NAME_SAILOR_KAVOC",		"en_US",	"Kavoc"),
		("LOC_CITY_NAME_SAILOR_WESTWALD",	"en_US",	"Westwald"),
		("LOC_CITY_NAME_SAILOR_CENTRAL_CITY", "en_US",	"Central City"),
		("LOC_CITY_NAME_SAILOR_DURAN",		"en_US",	"Duran"),	
		("LOC_CITY_NAME_SAILOR_RIESEVELT",	"en_US",	"Riesevelt"),		
		("LOC_CITY_NAME_SAILOR_HAFEN",		"en_US",	"Hafen"),			
		("LOC_CITY_NAME_SAILOR_FASSBINDER", "en_US",	"Fassbinder"),		
		("LOC_CITY_NAME_SAILOR_METTERBURG", "en_US",	"Metterburg");