-- // This version of the Atelier improvement is more stable in MP.
-- // This is not default.
-- // Improvement_YieldChanges
INSERT INTO Improvement_YieldChanges
		(ImprovementType,					YieldType,		YieldChange)
SELECT	'IMPROVEMENT_SAILOR_ATLEER_UI',		YieldType,		0
FROM Yields WHERE YieldType != 'YIELD_FAITH';

-- // Improvement_Adjacencies
INSERT INTO Improvement_Adjacencies
		(ImprovementType,					YieldChangeId)
VALUES	('IMPROVEMENT_SAILOR_ATLEER_UI',	'SAILOR_ATLEER_UI_LUXUR_CULTURE'),
		('IMPROVEMENT_SAILOR_ATLEER_UI',	'SAILOR_ATLEER_UI_LUXUR_GOLD'),
		('IMPROVEMENT_SAILOR_ATLEER_UI',	'SAILOR_ATLEER_UI_STRAT_SCIENCE'),
		('IMPROVEMENT_SAILOR_ATLEER_UI',	'SAILOR_ATLEER_UI_STRAT_GOLD'),
		('IMPROVEMENT_SAILOR_ATLEER_UI',	'SAILOR_ATLEER_UI_BONUS_FOOD'),
		('IMPROVEMENT_SAILOR_ATLEER_UI',	'SAILOR_ATLEER_UI_BONUS_PRODUCTION'),
		-- Chemistry
		('IMPROVEMENT_SAILOR_ATLEER_UI',	'SAILOR_ATLEER_UI_LUXUR_CULTURE_INCREASE'),
		('IMPROVEMENT_SAILOR_ATLEER_UI',	'SAILOR_ATLEER_UI_LUXUR_GOLD_INCREASE'),
		('IMPROVEMENT_SAILOR_ATLEER_UI',	'SAILOR_ATLEER_UI_STRAT_SCIENCE_INCREASE'),
		('IMPROVEMENT_SAILOR_ATLEER_UI',	'SAILOR_ATLEER_UI_STRAT_GOLD_INCREASE'),
		('IMPROVEMENT_SAILOR_ATLEER_UI',	'SAILOR_ATLEER_UI_BONUS_FOOD_INCREASE'),
		('IMPROVEMENT_SAILOR_ATLEER_UI',	'SAILOR_ATLEER_UI_BONUS_PRODUCTION_INCREASE');

-- // Adjacency_YieldChanges
INSERT INTO Adjacency_YieldChanges
		(ID,											Description,	YieldType,			YieldChange,	TilesRequired,	PrereqTech,			AdjacentResourceClass)
VALUES	('SAILOR_ATLEER_UI_LUXUR_CULTURE',				'Placeholder',	'YIELD_CULTURE',	1,				1,				NULL,				'RESOURCECLASS_LUXURY'),
		('SAILOR_ATLEER_UI_LUXUR_GOLD',					'Placeholder',	'YIELD_GOLD',		2,				1,				NULL,				'RESOURCECLASS_LUXURY'),
		('SAILOR_ATLEER_UI_STRAT_SCIENCE',				'Placeholder',	'YIELD_SCIENCE',	1,				1,				NULL,				'RESOURCECLASS_STRATEGIC'),
		('SAILOR_ATLEER_UI_STRAT_GOLD',					'Placeholder',	'YIELD_GOLD',		2,				1,				NULL,				'RESOURCECLASS_STRATEGIC'),
		('SAILOR_ATLEER_UI_BONUS_FOOD',					'Placeholder',	'YIELD_FOOD',		1,				1,				NULL,				'RESOURCECLASS_BONUS'),
		('SAILOR_ATLEER_UI_BONUS_PRODUCTION',			'Placeholder',	'YIELD_PRODUCTION',	1,				1,				NULL,				'RESOURCECLASS_BONUS'),
		-- Chemistry
		('SAILOR_ATLEER_UI_LUXUR_CULTURE_INCREASE',		'Placeholder',	'YIELD_CULTURE',	1,				1,				'TECH_CHEMISTRY',	'RESOURCECLASS_LUXURY'),
		('SAILOR_ATLEER_UI_LUXUR_GOLD_INCREASE',		'Placeholder',	'YIELD_GOLD',		2,				1,				'TECH_CHEMISTRY',	'RESOURCECLASS_LUXURY'),
		('SAILOR_ATLEER_UI_STRAT_SCIENCE_INCREASE',		'Placeholder',	'YIELD_SCIENCE',	1,				1,				'TECH_CHEMISTRY',	'RESOURCECLASS_STRATEGIC'),
		('SAILOR_ATLEER_UI_STRAT_GOLD_INCREASE',		'Placeholder',	'YIELD_GOLD',		2,				1,				'TECH_CHEMISTRY',	'RESOURCECLASS_STRATEGIC'),
		('SAILOR_ATLEER_UI_BONUS_FOOD_INCREASE',		'Placeholder',	'YIELD_FOOD',		1,				1,				'TECH_CHEMISTRY',	'RESOURCECLASS_BONUS'),
		('SAILOR_ATLEER_UI_BONUS_PRODUCTION_INCREASE',	'Placeholder',	'YIELD_PRODUCTION',	1,				1,				'TECH_CHEMISTRY',	'RESOURCECLASS_BONUS');